### ISSUE TITLE
trouble publishing pdf

### ISSUE THREAD

**Issue by abbood** [ashrafuzzaman/query_report#3]
I noticed that in your demo project gemfile, there aren't any dependencies for gems that generate pdfs (ie gem 'wkhtmltopdf-binary'
gem 'wicked_pdf'
gem 'pdfkit').. which makes me wonder how does query_report generate pdfs?

**Comment by ashrafuzzaman** [comment]
I used pdf prawn. You can see the dependency in the gemspec :)
Is there any issue you are finding to generate the PDF?

**Comment by abbood** [comment]
oh sorry i found out the answer to that as well but forgot to close the comment.. thanks!
