### ISSUE TITLE
how to control the action of search

### ISSUE THREAD

**Issue by abbood** [ashrafuzzaman/query_report#4]
I noticed by just putting a `filter` you get a search form.. However I'm not sure how to control the action of that search form (ie where the search form directs to).. 

so let's say i'm in admin/reports/daily.. if i hit search it automatically goes to admin/reports.. where do i control this kind of routing/action for the search form?

**Comment by ashrafuzzaman** [comment]
Here you can have an idea of how filters work.
http://ashrafuzzaman.github.io/query_report/articles/filter.html

The search form will automatically post to the same url. And it uses 'ransack' gem to do the filtering.
You don't need to configure router. You need to define how the filter will look like and in the controller  you need to define how the filter will work.
