### ISSUE TITLE
how to add time filtering to date filter?

### ISSUE THREAD

**Issue by abbood** [ashrafuzzaman/query_report#9]
the way **query report** is made is that it auto generates a date filer (it uses bootstrap-datepicker).. i will need to add a time picker as well.. there is a [gem](https://github.com/lubieniebieski/bootstrap-datetimepicker-rails) for that as well.. how can i do this? will i have to build my own gem? :warning:

**Comment by ashrafuzzaman** [comment]
You can override the helper that generates the filters by cpoying query_report_filter_helper.rb from the gem and then you can override the filters.

**Comment by ashrafuzzaman** [comment]
You can define `query_report_date_filter` in helpers as following,

``` ruby
def query_report_date_filter(name, value, options={})
    text_field_tag name, value, :class => 'datepicker'
end
```

For details please view the [wiki](https://github.com/ashrafuzzaman/query_report/wiki/Filter)
